# Test HTTP requests

### use with: REST Client extension

@apiurl = http://localhost:3000/api

### GET all items

GET {{apiurl}}/items

### Add new item

POST {{apiurl}}/items
Content-Type: application/json

{"name": "Kaurahiutale"}

### GET item by ID
GET {{apiurl}}/items/1

### Update item by ID
PUT {{apiurl}}/items/3
Content-Type: application/json

{"name": "Pähkinä"}

### DELETE item by ID
DELETE {{apiurl}}/items/2
